name: 'Setup Scanner CLI for SonarQube (Server, Cloud)'
description:
  'GitHub Actions to setup Scanner CLI for SonarQube (Server, Cloud) and add it
  to PATH'
author: SylvainDumas

branding:
  icon: package
  color: red

# Define your inputs here.
inputs:
  version:
    description: 'The version to install'
    default: '7.0.2.4839'
    required: false

runs:
  using: node20
  main: dist/index.js
