name: 'Setup Sonarqube scanner cli'
description: 'Setup Sonarqube scanner cli and add it to the PATH'
author: SylvainDumas

branding:
  icon: package
  color: red

# Define your inputs here.
inputs:
  version:
    description: 'The version of the package to install'
    required: true

runs:
  using: node20
  main: dist/index.js
